// Auto-generated; combines local logo assets with legacy Clearbit fallbacks
export interface CollegeEntry {
  name: string
  slug: string
  conference: string
  division: "FBS" | "FCS" | "Other"
  logo: string
}

export const collegeEntries: CollegeEntry[] = [
  {
    name: 'Got1',
    slug: 'got1',
    conference: 'Independent',
    division: 'Other',
    logo: '/got1-logos/got1-icon.png',
  },
  {
    name: 'East Carolina University',
    slug: 'ecu',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/ecu.svg',
  },
  {
    name: 'Florida Atlantic University',
    slug: 'fau',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/fau.svg',
  },
  {
    name: 'Rice University',
    slug: 'rice',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/rice.svg',
  },
  {
    name: 'Temple University',
    slug: 'temple',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/temple.svg',
  },
  {
    name: 'Tulane University',
    slug: 'tulane',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/tulane.svg',
  },
  {
    name: 'United States Naval Academy',
    slug: 'navy',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/navy.svg',
  },
  {
    name: 'University of Alabama at Birmingham',
    slug: 'uab',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/uab.svg',
  },
  {
    name: 'University of Memphis',
    slug: 'memphis',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/memphis.svg',
  },
  {
    name: 'University of North Carolina at Charlotte',
    slug: 'charlotte',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/charlotte.svg',
  },
  {
    name: 'University of North Texas',
    slug: 'northern-texas',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/northern-texas.svg',
  },
  {
    name: 'University of South Florida',
    slug: 'usf',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/usf.svg',
  },
  {
    name: 'University of Texas at San Antonio',
    slug: 'utsa',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/utsa.svg',
  },
  {
    name: 'University of Tulsa',
    slug: 'tulsa',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/tulsa.svg',
  },
  {
    name: 'Boston College',
    slug: 'boston-college',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/boston-college.svg',
  },
  {
    name: 'Clemson University',
    slug: 'clemson',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/clemson.svg',
  },
  {
    name: 'Duke University',
    slug: 'duke',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/duke.svg',
  },
  {
    name: 'Florida State University',
    slug: 'florida-state',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/florida-state.svg',
  },
  {
    name: 'Georgia Institute of Technology',
    slug: 'georgia-tech',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/georgia-tech.svg',
  },
  {
    name: 'NC State University',
    slug: 'nc-state-university',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/nc-state-university.svg',
  },
  {
    name: 'North Carolina State University',
    slug: 'nc-state',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/nc-state.svg',
  },
  {
    name: 'Southern Methodist University',
    slug: 'smu',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/smu.svg',
  },
  {
    name: 'Stanford University',
    slug: 'stanford',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/stanford.svg',
  },
  {
    name: 'Syracuse University',
    slug: 'syracuse',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/syracuse.svg',
  },
  {
    name: 'University of California, Berkeley',
    slug: 'cal',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/cal.svg',
  },
  {
    name: 'University of Louisville',
    slug: 'louisville',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/louisville.svg',
  },
  {
    name: 'University of Miami',
    slug: 'miami-florida',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/miami-florida.svg',
  },
  {
    name: 'University of North Carolina',
    slug: 'north-carolina',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/north-carolina.svg',
  },
  {
    name: 'University of Pittsburgh',
    slug: 'pitt',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/pitt.svg',
  },
  {
    name: 'University of Virginia',
    slug: 'virginia',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/virginia.svg',
  },
  {
    name: 'Virginia Polytechnic Institute and State University',
    slug: 'virginia-tech',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/virginia-tech.svg',
  },
  {
    name: 'Wake Forest University',
    slug: 'wake-forest',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/wake-forest.svg',
  },
  {
    name: 'Arizona State University',
    slug: 'arizona-state',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/arizona-state.svg',
  },
  {
    name: 'Baylor University',
    slug: 'baylor',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/baylor.svg',
  },
  {
    name: 'Brigham Young University',
    slug: 'byu',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/byu.svg',
  },
  {
    name: 'Iowa State University',
    slug: 'iowas-state',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/iowas-state.svg',
  },
  {
    name: 'Kansas State University',
    slug: 'kansas-state',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/kansas-state.svg',
  },
  {
    name: 'Oklahoma State University',
    slug: 'oklahoma-state',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/oklahoma-state.svg',
  },
  {
    name: 'Texas Christian University',
    slug: 'tcu',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/tcu.svg',
  },
  {
    name: 'Texas Tech University',
    slug: 'texas-tech',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/texas-tech.svg',
  },
  {
    name: 'University of Arizona',
    slug: 'arizona',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/arizona.svg',
  },
  {
    name: 'University of Central Florida',
    slug: 'ucf',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/ucf.svg',
  },
  {
    name: 'University of Cincinnati',
    slug: 'cincinatti-bearcats',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/cincinatti-bearcats.svg',
  },
  {
    name: 'University of Colorado',
    slug: 'colorado-buffaloes',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/colorado-buffaloes.svg',
  },
  {
    name: 'University of Houston',
    slug: 'houston',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/houston.svg',
  },
  {
    name: 'University of Kansas',
    slug: 'kansas',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/kansas.svg',
  },
  {
    name: 'University of Utah',
    slug: 'utah',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/utah.svg',
  },
  {
    name: 'West Virginia University',
    slug: 'west-virginia',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/west-virginia.svg',
  },
  {
    name: 'Indiana University',
    slug: 'indiana-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/indiana-university.svg',
  },
  {
    name: 'Michigan State University',
    slug: 'michigan-state-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/michigan-state-university.svg',
  },
  {
    name: 'Northwestern University',
    slug: 'northwestern-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/northwestern-university.svg',
  },
  {
    name: 'Ohio State University',
    slug: 'ohio-state-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/ohio-state-university.svg',
  },
  {
    name: 'Penn State University',
    slug: 'penn-state-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/penn-state-university.svg',
  },
  {
    name: 'Purdue University',
    slug: 'purdue-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/purdue-university.svg',
  },
  {
    name: 'Rutgers University',
    slug: 'rutgers-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/rutgers-university.svg',
  },
  {
    name: 'University of Illinois',
    slug: 'university-of-illinois',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-illinois.svg',
  },
  {
    name: 'University of Iowa',
    slug: 'university-of-iowa',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-iowa.svg',
  },
  {
    name: 'University of Maryland',
    slug: 'university-of-maryland',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-maryland.svg',
  },
  {
    name: 'University of Michigan',
    slug: 'university-of-michigan',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-michigan.svg',
  },
  {
    name: 'University of Minnesota',
    slug: 'university-of-minnesota',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-minnesota.svg',
  },
  {
    name: 'University of Nebraska',
    slug: 'university-of-nebraska',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-nebraska.svg',
  },
  {
    name: 'University of Wisconsin',
    slug: 'university-of-wisconsin',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-wisconsin.svg',
  },
  {
    name: 'Florida International University',
    slug: 'fiu',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/fiu.svg',
  },
  {
    name: 'Jacksonville State University',
    slug: 'jsu',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/jsu.svg',
  },
  {
    name: 'Liberty University',
    slug: 'liberty',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/liberty.svg',
  },
  {
    name: 'Louisiana Tech University',
    slug: 'la-tech',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/la-tech.svg',
  },
  {
    name: 'Middle Tennessee State University',
    slug: 'middle-tennessee',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/middle-tennessee.svg',
  },
  {
    name: 'Sam Houston State University',
    slug: 'sam-houston',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/sam-houston.svg',
  },
  {
    name: 'University of Texas at El Paso',
    slug: 'utep',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/utep.svg',
  },
  {
    name: 'Western Kentucky University',
    slug: 'western-kentucky-hilltopers',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/western-kentucky-hilltopers.svg',
  },
  {
    name: 'United States Military Academy',
    slug: 'army',
    conference: 'FBS Independents',
    division: 'FBS',
    logo: '/got1-logos/college/independent/army.svg',
  },
  {
    name: 'University of Connecticut',
    slug: 'uconn',
    conference: 'FBS Independents',
    division: 'FBS',
    logo: '/got1-logos/college/independent/uconn.svg',
  },
  {
    name: 'University of Massachusetts Amherst',
    slug: 'umass',
    conference: 'FBS Independents',
    division: 'FBS',
    logo: '/got1-logos/college/independent/umass.svg',
  },
  {
    name: 'University of Notre Dame',
    slug: 'notre-dame',
    conference: 'FBS Independents',
    division: 'FBS',
    logo: '/got1-logos/college/independent/notre-dame.svg',
  },
  {
    name: 'Ball State University',
    slug: 'ball-state',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/ball-state.svg',
  },
  {
    name: 'Bowling Green State University',
    slug: 'bowling-green',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/bowling-green.svg',
  },
  {
    name: 'Central Michigan University',
    slug: 'central-michigan',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/central-michigan.svg',
  },
  {
    name: 'Eastern Michigan University',
    slug: 'eastern-michigan',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/eastern-michigan.svg',
  },
  {
    name: 'Kent State University',
    slug: 'kent-state',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/kent-state.svg',
  },
  {
    name: 'Miami University',
    slug: 'miami-ohio',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/miami-ohio.svg',
  },
  {
    name: 'Northern Illinois University',
    slug: 'niu',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/niu.svg',
  },
  {
    name: 'Ohio University',
    slug: 'ohio-bobcats',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/ohio-bobcats.svg',
  },
  {
    name: 'University at Buffalo',
    slug: 'buffalo',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/buffalo.svg',
  },
  {
    name: 'University of Akron',
    slug: 'akron',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/akron.svg',
  },
  {
    name: 'University of Toledo',
    slug: 'toledo',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/toledo.svg',
  },
  {
    name: 'Western Michigan University',
    slug: 'western-michigan',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/western-michigan.svg',
  },
  {
    name: 'Boise State University',
    slug: 'boise-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/boise-state.svg',
  },
  {
    name: 'California State University, Fresno',
    slug: 'fresno-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/fresno-state.svg',
  },
  {
    name: 'Colorado State University',
    slug: 'colorado-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/colorado-state.svg',
  },
  {
    name: 'New Mexico State University',
    slug: 'new-mexico-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/new-mexico-state.svg',
  },
  {
    name: 'San Diego State University',
    slug: 'san-diego',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/san-diego.svg',
  },
  {
    name: 'San José State University',
    slug: 'san-jose-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/san-jose-state.svg',
  },
  {
    name: 'United States Air Force Academy',
    slug: 'air-force',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/air-force.svg',
  },
  {
    name: 'University of Hawai‘i at Mānoa',
    slug: 'hawaii',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/hawaii.svg',
  },
  {
    name: 'University of Nevada',
    slug: 'nevada',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/nevada.svg',
  },
  {
    name: 'University of Nevada, Las Vegas',
    slug: 'unlv',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/unlv.svg',
  },
  {
    name: 'University of Wyoming',
    slug: 'wyoming',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/wyoming.svg',
  },
  {
    name: 'Utah State University',
    slug: 'utah-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/utah-state.svg',
  },
  {
    name: 'Oregon State University',
    slug: 'oregon-state',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/oregon-state.svg',
  },
  {
    name: 'University of California, Los Angeles',
    slug: 'university-of-california-los-angeles',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/university-of-california-los-angeles.svg',
  },
  {
    name: 'University of Oregon',
    slug: 'university-of-oregon',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/university-of-oregon.svg',
  },
  {
    name: 'University of Southern California',
    slug: 'university-of-southern-california',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/university-of-southern-california.svg',
  },
  {
    name: 'University of Washington',
    slug: 'university-of-washington',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/university-of-washington.svg',
  },
  {
    name: 'Washington State University',
    slug: 'washington-state',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/washington-state.svg',
  },
  {
    name: 'Auburn University',
    slug: 'auburn-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/auburn-university.svg',
  },
  {
    name: 'Louisiana State University',
    slug: 'louisiana-state-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/louisiana-state-university.svg',
  },
  {
    name: 'Mississippi State University',
    slug: 'mississippi-state-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/mississippi-state-university.svg',
  },
  {
    name: 'Texas A&M University',
    slug: 'texas-aandm-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/texas-aandm-university.svg',
  },
  {
    name: 'University of Alabama',
    slug: 'university-of-alabama',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-alabama.svg',
  },
  {
    name: 'University of Arkansas',
    slug: 'university-of-arkansas',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-arkansas.svg',
  },
  {
    name: 'University of Florida',
    slug: 'university-of-florida',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-florida.svg',
  },
  {
    name: 'University of Georgia',
    slug: 'university-of-georgia',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-georgia.svg',
  },
  {
    name: 'University of Kentucky',
    slug: 'university-of-kentucky',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-kentucky.svg',
  },
  {
    name: 'University of Mississippi',
    slug: 'university-of-mississippi',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-mississippi.svg',
  },
  {
    name: 'University of Missouri',
    slug: 'university-of-missouri',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-missouri.svg',
  },
  {
    name: 'University of Oklahoma',
    slug: 'university-of-oklahoma',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-oklahoma.svg',
  },
  {
    name: 'University of South Carolina',
    slug: 'university-of-south-carolina',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-south-carolina.svg',
  },
  {
    name: 'University of Tennessee',
    slug: 'university-of-tennessee',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-tennessee.svg',
  },
  {
    name: 'University of Texas',
    slug: 'university-of-texas',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-texas.svg',
  },
  {
    name: 'Vanderbilt University',
    slug: 'vanderbilt-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/vanderbilt-university.svg',
  },
  {
    name: 'Appalachian State University',
    slug: 'app-state',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/app-state.svg',
  },
  {
    name: 'Arkansas State University',
    slug: 'arkansas-state-red-wolves',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/arkansas-state-red-wolves.svg',
  },
  {
    name: 'Coastal Carolina University',
    slug: 'coastal-carolina',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/coastal-carolina.svg',
  },
  {
    name: 'Georgia Southern University',
    slug: 'georgia-southern',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/georgia-southern.svg',
  },
  {
    name: 'Georgia State University',
    slug: 'georgia-state',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/georgia-state.svg',
  },
  {
    name: 'James Madison University',
    slug: 'jmu',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/jmu.svg',
  },
  {
    name: 'Marshall University',
    slug: 'marshall',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/marshall.svg',
  },
  {
    name: 'Old Dominion University',
    slug: 'old-dominion',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/old-dominion.svg',
  },
  {
    name: 'Texas State University',
    slug: 'texas-state',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/texas-state.svg',
  },
  {
    name: 'Troy University',
    slug: 'troy',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/troy.svg',
  },
  {
    name: 'University of Louisiana at Lafayette',
    slug: 'louisiana-ragin-cajuns',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/louisiana-ragin-cajuns.svg',
  },
  {
    name: 'University of Louisiana at Monroe',
    slug: 'louisiana-monroe',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/louisiana-monroe.svg',
  },
  {
    name: 'University of South Alabama',
    slug: 'south-alabama',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/south-alabama.svg',
  },
  {
    name: 'University of Southern Mississippi',
    slug: 'southern-miss',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/southern-miss.svg',
  },
  {
    name: 'California Polytechnic State University',
    slug: 'cal-poly-mustangs',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/cal-poly-mustangs.svg',
  },
  {
    name: 'California State University, Sacramento',
    slug: 'sacramento-state-hornets',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/sacramento-state-hornets.svg',
  },
  {
    name: 'Eastern Washington University',
    slug: 'eastern-washington',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/eastern-washington.svg',
  },
  {
    name: 'Idaho State University',
    slug: 'idaho-state',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/idaho-state.svg',
  },
  {
    name: 'Montana State University',
    slug: 'montana-state',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/montana-state.svg',
  },
  {
    name: 'Northern Arizona University',
    slug: 'northern-arizona-lumberjacks',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/northern-arizona-lumberjacks.svg',
  },
  {
    name: 'Portland State University',
    slug: 'portland-state-vikings',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/portland-state-vikings.svg',
  },
  {
    name: 'University of California, Davis',
    slug: 'uc-davis-aggies',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/uc-davis-aggies.svg',
  },
  {
    name: 'University of Idaho',
    slug: 'idaho-vandals',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/idaho-vandals.svg',
  },
  {
    name: 'University of Montana',
    slug: 'montana-grizzlies',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/montana-grizzlies.svg',
  },
  {
    name: 'University of Northern Colorado',
    slug: 'northern-colorado-bears',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/northern-colorado-bears.svg',
  },
  {
    name: 'Weber State University',
    slug: 'weber-state-wildcats',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/weber-state-wildcats.svg',
  },
  {
    name: 'Charleston Southern University',
    slug: 'charleston-southern',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/charleston-southern.svg',
  },
  {
    name: 'Eastern Illinois University',
    slug: 'eastern-illinois',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/eastern-illinois.svg',
  },
  {
    name: 'Gardner-Webb University',
    slug: 'gardner-web',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/gardner-web.svg',
  },
  {
    name: 'Southeast Missouri State University',
    slug: 'southeast-missouri-redhawks',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/southeast-missouri-redhawks.svg',
  },
  {
    name: 'Tennessee State University',
    slug: 'tennessee-state-university',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/tennessee-state-university.svg',
  },
  {
    name: 'Tennessee Technological University',
    slug: 'tennessee-tech-golden-eagles',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/tennessee-tech-golden-eagles.svg',
  },
  {
    name: 'University of Tennessee at Martin',
    slug: 'ut-martin-skyhawks',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/ut-martin-skyhawks.svg',
  },
  {
    name: 'Western Illinois University',
    slug: 'western-illinois-leathernecks',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/western-illinois-leathernecks.svg',
  },
  {
    name: 'Campbell University',
    slug: 'campbell-camels',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/campbell-camels.svg',
  },
  {
    name: 'Elon University',
    slug: 'elon',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/elon.svg',
  },
  {
    name: 'Hampton University',
    slug: 'hampton-pirates',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/hampton-pirates.svg',
  },
  {
    name: 'Howard University',
    slug: 'howard-bison-logo',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/howard-bison-logo.svg',
  },
  {
    name: 'Monmouth University',
    slug: 'monmouth',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/monmouth.svg',
  },
  {
    name: 'North Carolina A&T State University',
    slug: 'north-carolina-a-t',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/north-carolina-a-t.svg',
  },
  {
    name: 'Stony Brook University',
    slug: 'stony-brook-seawolves',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/stony-brook-seawolves.svg',
  },
  {
    name: 'Towson University',
    slug: 'towson-tigers',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/towson-univrersity.svg',
  },
  {
    name: 'University at Albany',
    slug: 'ualbany-great-danes',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/ualbany-great-danes.svg',
  },
  {
    name: 'University of Delaware',
    slug: 'delaware-fighting-hens',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/delaware-fighting-hens.svg',
  },
  {
    name: 'University of Maine',
    slug: 'maine-black-bears',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/maine-black-bears.svg',
  },
  {
    name: 'University of New Hampshire',
    slug: 'new-hampshire-wildcats',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/new-hampshire-wildcats.svg',
  },
  {
    name: 'University of Rhode Island',
    slug: 'rhode-island-rams',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/rhode-island-rams.svg',
  },
  {
    name: 'University of Richmond',
    slug: 'richmond-spiders',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/richmond-spiders.svg',
  },
  {
    name: 'Villanova University',
    slug: 'villanova',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/villanova.svg',
  },
  {
    name: 'William & Mary',
    slug: 'william-and-mary',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/william-and-mary.svg',
  },
  {
    name: 'Brown University',
    slug: 'brown',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/brown.svg',
  },
  {
    name: 'Columbia University',
    slug: 'columbia',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/columbia.svg',
  },
  {
    name: 'Cornell University',
    slug: 'cornell',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/cornell.svg',
  },
  {
    name: 'Dartmouth College',
    slug: 'dartmouth',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/dartmouth.svg',
  },
  {
    name: 'Harvard University',
    slug: 'harvard',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/harvard.svg',
  },
  {
    name: 'Princeton University',
    slug: 'princeton',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/princeton.svg',
  },
  {
    name: 'University of Pennsylvania',
    slug: 'penn',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/penn.svg',
  },
  {
    name: 'Yale University',
    slug: 'yale',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/yale.svg',
  },
  {
    name: 'Illinois State University',
    slug: 'illinois-state',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/illinois-state.svg',
  },
  {
    name: 'Missouri State University',
    slug: 'missouri-state-bears',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/missouri-state-bears.svg',
  },
  {
    name: 'Murray State University',
    slug: 'murray-state',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/murray-state.svg',
  },
  {
    name: 'North Dakota State University',
    slug: 'north-dakota-state-university-ndsu',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/north-dakota-state-university-ndsu.svg',
  },
  {
    name: 'South Dakota State University',
    slug: 'south-dakota-jack-rabbits',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/south-dakota-jack-rabbits.svg',
  },
  {
    name: 'Southern Illinois University',
    slug: 'southern-illinois-salukis',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/southern-illinois-salukis.svg',
  },
  {
    name: 'University of North Dakota',
    slug: 'north-dakota-fighting-hawks',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/north-dakota-fighting-hawks.svg',
  },
  {
    name: 'University of Northern Iowa',
    slug: 'northern-iowa',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/northern-iowa.svg',
  },
  {
    name: 'University of South Dakota',
    slug: 'south-dakota',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/south-dakota.svg',
  },
  {
    name: 'Central Connecticut State University',
    slug: 'central-connecticut',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/central-connecticut.svg',
  },
  {
    name: 'Duquesne University',
    slug: 'duquesne',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/duquesne.svg',
  },
  {
    name: 'Long Island University',
    slug: 'liu-sharks',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/liu-sharks.svg',
  },
  {
    name: 'Merrimack College',
    slug: 'merrimack-warriors',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/merrimack-warriors-logo.svg',
  },
  {
    name: 'Sacred Heart University',
    slug: 'sacred-heart-shu',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/sacred-heart-shuz.svg',
  },
  {
    name: 'Saint Francis University',
    slug: 'saint-francis-red-flashes',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/saint-francis-red-flashes.svg',
  },
  {
    name: 'Stonehill College',
    slug: 'stonehill-skyhawks',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/stonehill-skyhawks.svg',
  },
  {
    name: 'Wagner College',
    slug: 'wagner-seahawks',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/wagner-seahawks.svg',
  },
  {
    name: 'Bucknell University',
    slug: 'bucknell',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/bucknell.svg',
  },
  {
    name: 'Colgate University',
    slug: 'colgate',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/colgate.svg',
  },
  {
    name: 'College of the Holy Cross',
    slug: 'holy-cross',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/holy-cross.svg',
  },
  {
    name: 'Georgetown University',
    slug: 'georgetown-hoyas',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/georgetown-hoyas.svg',
  },
  {
    name: 'Lafayette College',
    slug: 'lafayette',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/lafayette.svg',
  },
  {
    name: 'Lehigh University',
    slug: 'lehigh',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/lehigh.svg',
  },
  {
    name: 'Butler University',
    slug: 'butler',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/butler.svg',
  },
  {
    name: 'Davidson College',
    slug: 'davidson',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/davidson.svg',
  },
  {
    name: 'Drake University',
    slug: 'drake',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/drake.svg',
  },
  {
    name: 'Marist College',
    slug: 'marist-red-foxes',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/marist-red-foxes.svg',
  },
  {
    name: 'Morehead State University',
    slug: 'morehead-state-eagles',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/morehead-state-eagles.svg',
  },
  {
    name: 'Presbyterian College',
    slug: 'presbyterian-blue-hose',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/presbyterian-blue-hose.svg',
  },
  {
    name: 'Stetson University',
    slug: 'stetson-hatters',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/stetson-hatters.svg',
  },
  {
    name: 'University of Dayton',
    slug: 'dayton',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/dayton.svg',
  },
  {
    name: 'University of San Diego',
    slug: 'san-diego-toreros',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/san-diego-toreros.svg',
  },
  {
    name: 'Valparaiso University',
    slug: 'valpo',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/valpo.svg',
  },
  {
    name: 'East Tennessee State University',
    slug: 'east-tennessee-state-buccaneers',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/east-tennessee-state-buccaneers.svg',
  },
  {
    name: 'Furman University',
    slug: 'furman',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/furman.svg',
  },
  {
    name: 'Mercer University',
    slug: 'mercer-bears',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/mercer-bears.svg',
  },
  {
    name: 'Samford University',
    slug: 'samford',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/samford.svg',
  },
  {
    name: 'The Citadel',
    slug: 'citadel',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/citadel.svg',
  },
  {
    name: 'University of Tennessee at Chattanooga',
    slug: 'chatanooga',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/chatanooga.svg',
  },
  {
    name: 'Virginia Military Institute',
    slug: 'vmi-keydets',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/vmi-keydets.svg',
  },
  {
    name: 'Western Carolina University',
    slug: 'western-carolina-catamounts',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/western-carolina-catamounts.svg',
  },
  {
    name: 'Wofford College',
    slug: 'wofford',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/wofford.svg',
  },
  {
    name: 'Houston Christian University',
    slug: 'houston-christian-huskies',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/houston-christian-huskies.svg',
  },
  {
    name: 'Lamar University',
    slug: 'lamar',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/lamar.svg',
  },
  {
    name: 'McNeese State University',
    slug: 'mcneese-state-cowboys',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/mcneese-state-cowboys.svg',
  },
  {
    name: 'Nicholls State University',
    slug: 'nicholls',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/nicholls.svg',
  },
  {
    name: 'Northwestern State University',
    slug: 'northwestern-state-demons',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/northwestern-state-demons.svg',
  },
  {
    name: 'Southeastern Louisiana University',
    slug: 'southeastern-louisiana-lions',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/southeastern-louisiana-lions.svg',
  },
  {
    name: 'Stephen F. Austin State University',
    slug: 'stephen-f-autin',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/stephen-f-autin.svg',
  },
  {
    name: 'Texas A&M University–Commerce',
    slug: 'texas-a-m-commerce-lions',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/texas-a-m-commerce-lions.svg',
  },
  {
    name: 'University of the Incarnate Word',
    slug: 'incarnate-word-cardinals',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/incarnate-word-cardinals.svg',
  },
  {
    name: 'Alabama A&M University',
    slug: 'alabama-a-m',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/alabama-a-m.svg',
  },
  {
    name: 'Bethune-Cookman University',
    slug: 'bethune-cookman-bcu',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/bethune-cookman-bcu.svg',
  },
  {
    name: 'Florida A&M University',
    slug: 'famu',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/famu.svg',
  },
  {
    name: 'Grambling State University',
    slug: 'grambling',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/grambling.svg',
  },
  {
    name: 'Jackson State University',
    slug: 'jackson-state-university-jsu',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/jackson-state-university-jsu.svg',
  },
  {
    name: 'Mississippi Valley State University',
    slug: 'mississippi-valley-state-delta-devils',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/mississippi-valley-state-delta-devils.svg',
  },
  {
    name: 'Prairie View A&M University',
    slug: 'praire-view-a-m',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/praire-view-a-m.svg',
  },
  {
    name: 'Southern University',
    slug: 'southern-jaguars',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/southern-jaguars.svg',
  },
  {
    name: 'Texas Southern University',
    slug: 'texas-southern-tigers',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/texas-southern-tigers.svg',
  },
  {
    name: 'University of Arkansas at Pine Bluff',
    slug: 'arkansas-pine-bluff',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/arkansas-pine-bluff.svg',
  },
  {
    name: 'Abilene Christian University',
    slug: 'abeline-christian-acu',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/abeline-christian-acu.svg',
  },
  {
    name: 'Austin Peay State University',
    slug: 'austin-paey',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/austin-paey.svg',
  },
  {
    name: 'Eastern Kentucky University',
    slug: 'eastern-kentucky',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/eastern-kentucky.svg',
  },
  {
    name: 'Southern Utah University',
    slug: 'southern-utah-thunderbirds',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/southern-utah-thunderbirds.svg',
  },
  {
    name: 'Tarleton State University',
    slug: 'tarleton-state-texans',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/tarleton-state-texans.svg',
  },
  {
    name: 'University of Central Arkansas',
    slug: 'university-central-arkansas',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/university-central-arkansas.svg',
  },
  {
    name: 'University of North Alabama',
    slug: 'north-alabama',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/north-alabama.svg',
  },
  {
    name: 'University of West Georgia',
    slug: 'west-georgia-wolves',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/west-georgia-wolves.svg',
  },
  {
    name: 'Utah Tech University',
    slug: 'utah-tech',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/utah-tech.svg',
  },
]
