// Auto-generated; combines local logo assets with legacy Clearbit fallbacks
export interface CollegeEntry {
  name: string
  slug: string
  conference: string
  division: "FBS" | "FCS" | "D2" | "D3" | "NAIA" | "NFL" | "Other"
  logo: string
}

export const collegeEntries: CollegeEntry[] = [
  {
    name: 'Got1',
    slug: 'got1',
    conference: 'Independent',
    division: 'Other',
    logo: '/got1-logos/got1-icon.png',
  },
  {
    name: 'East Carolina University',
    slug: 'ecu',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/ecu.svg',
  },
  {
    name: 'Florida Atlantic University',
    slug: 'fau',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/fau.svg',
  },
  {
    name: 'Rice University',
    slug: 'rice',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/rice.svg',
  },
  {
    name: 'Temple University',
    slug: 'temple',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/temple.svg',
  },
  {
    name: 'Tulane University',
    slug: 'tulane',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/tulane.svg',
  },
  {
    name: 'United States Naval Academy',
    slug: 'navy',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/navy.svg',
  },
  {
    name: 'University of Alabama at Birmingham',
    slug: 'uab',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/uab.svg',
  },
  {
    name: 'University of Memphis',
    slug: 'memphis',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/memphis.svg',
  },
  {
    name: 'University of North Carolina at Charlotte',
    slug: 'charlotte',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/charlotte.svg',
  },
  {
    name: 'University of North Texas',
    slug: 'northern-texas',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/northern-texas.svg',
  },
  {
    name: 'University of South Florida',
    slug: 'usf',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/usf.svg',
  },
  {
    name: 'University of Texas at San Antonio',
    slug: 'utsa',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/utsa.svg',
  },
  {
    name: 'University of Tulsa',
    slug: 'tulsa',
    conference: 'American Athletic Conference',
    division: 'FBS',
    logo: '/got1-logos/college/aac/tulsa.svg',
  },
  {
    name: 'Boston College',
    slug: 'boston-college',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/boston-college.svg',
  },
  {
    name: 'Clemson University',
    slug: 'clemson',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/clemson.svg',
  },
  {
    name: 'Duke University',
    slug: 'duke',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/duke.svg',
  },
  {
    name: 'Florida State University',
    slug: 'florida-state',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/florida-state.svg',
  },
  {
    name: 'Georgia Institute of Technology',
    slug: 'georgia-tech',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/georgia-tech.svg',
  },
  {
    name: 'NC State University',
    slug: 'nc-state-university',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/nc-state-university.svg',
  },
  {
    name: 'North Carolina State University',
    slug: 'nc-state',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/nc-state.svg',
  },
  {
    name: 'Southern Methodist University',
    slug: 'smu',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/smu.svg',
  },
  {
    name: 'Stanford University',
    slug: 'stanford',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/stanford.svg',
  },
  {
    name: 'Syracuse University',
    slug: 'syracuse',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/syracuse.svg',
  },
  {
    name: 'University of California, Berkeley',
    slug: 'cal',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/cal.svg',
  },
  {
    name: 'University of Louisville',
    slug: 'louisville',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/louisville.svg',
  },
  {
    name: 'University of Miami',
    slug: 'miami-florida',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/miami-florida.svg',
  },
  {
    name: 'University of North Carolina',
    slug: 'north-carolina',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/north-carolina.svg',
  },
  {
    name: 'University of Pittsburgh',
    slug: 'pitt',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/pitt.svg',
  },
  {
    name: 'University of Virginia',
    slug: 'virginia',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/virginia.svg',
  },
  {
    name: 'Virginia Polytechnic Institute and State University',
    slug: 'virginia-tech',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/virginia-tech.svg',
  },
  {
    name: 'Wake Forest University',
    slug: 'wake-forest',
    conference: 'Atlantic Coast Conference',
    division: 'FBS',
    logo: '/got1-logos/college/acc/wake-forest.svg',
  },
  {
    name: 'Arizona State University',
    slug: 'arizona-state',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/arizona-state.svg',
  },
  {
    name: 'Baylor University',
    slug: 'baylor',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/baylor.svg',
  },
  {
    name: 'Brigham Young University',
    slug: 'byu',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/byu.svg',
  },
  {
    name: 'Iowa State University',
    slug: 'iowas-state',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/iowas-state.svg',
  },
  {
    name: 'Kansas State University',
    slug: 'kansas-state',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/kansas-state.svg',
  },
  {
    name: 'Oklahoma State University',
    slug: 'oklahoma-state',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/oklahoma-state.svg',
  },
  {
    name: 'Texas Christian University',
    slug: 'tcu',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/tcu.svg',
  },
  {
    name: 'Texas Tech University',
    slug: 'texas-tech',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/texas-tech.svg',
  },
  {
    name: 'University of Arizona',
    slug: 'arizona',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/arizona.svg',
  },
  {
    name: 'University of Central Florida',
    slug: 'ucf',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/ucf.svg',
  },
  {
    name: 'University of Cincinnati',
    slug: 'cincinatti-bearcats',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/cincinatti-bearcats.svg',
  },
  {
    name: 'University of Colorado',
    slug: 'colorado-buffaloes',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/colorado-buffaloes.svg',
  },
  {
    name: 'University of Houston',
    slug: 'houston',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/houston.svg',
  },
  {
    name: 'University of Kansas',
    slug: 'kansas',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/kansas.svg',
  },
  {
    name: 'University of Utah',
    slug: 'utah',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/utah.svg',
  },
  {
    name: 'West Virginia University',
    slug: 'west-virginia',
    conference: 'Big 12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big12/west-virginia.svg',
  },
  {
    name: 'Indiana University',
    slug: 'indiana-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/indiana-university.svg',
  },
  {
    name: 'Michigan State University',
    slug: 'michigan-state-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/michigan-state-university.svg',
  },
  {
    name: 'Northwestern University',
    slug: 'northwestern-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/northwestern-university.svg',
  },
  {
    name: 'Ohio State University',
    slug: 'ohio-state-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/ohio-state-university.svg',
  },
  {
    name: 'Penn State University',
    slug: 'penn-state-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/penn-state-university.svg',
  },
  {
    name: 'Purdue University',
    slug: 'purdue-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/purdue-university.svg',
  },
  {
    name: 'Rutgers University',
    slug: 'rutgers-university',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/rutgers-university.svg',
  },
  {
    name: 'University of Illinois',
    slug: 'university-of-illinois',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-illinois.svg',
  },
  {
    name: 'University of Iowa',
    slug: 'university-of-iowa',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-iowa.svg',
  },
  {
    name: 'University of Maryland',
    slug: 'university-of-maryland',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-maryland.svg',
  },
  {
    name: 'University of Michigan',
    slug: 'university-of-michigan',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-michigan.svg',
  },
  {
    name: 'University of Minnesota',
    slug: 'university-of-minnesota',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-minnesota.svg',
  },
  {
    name: 'University of Nebraska',
    slug: 'university-of-nebraska',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-nebraska.svg',
  },
  {
    name: 'University of Wisconsin',
    slug: 'university-of-wisconsin',
    conference: 'Big Ten Conference',
    division: 'FBS',
    logo: '/got1-logos/college/big10/university-of-wisconsin.svg',
  },
  {
    name: 'Florida International University',
    slug: 'fiu',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/fiu.svg',
  },
  {
    name: 'Jacksonville State University',
    slug: 'jsu',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/jsu.svg',
  },
  {
    name: 'Liberty University',
    slug: 'liberty',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/liberty.svg',
  },
  {
    name: 'Louisiana Tech University',
    slug: 'la-tech',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/la-tech.svg',
  },
  {
    name: 'Middle Tennessee State University',
    slug: 'middle-tennessee',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/middle-tennessee.svg',
  },
  {
    name: 'Sam Houston State University',
    slug: 'sam-houston',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/sam-houston.svg',
  },
  {
    name: 'University of Texas at El Paso',
    slug: 'utep',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/utep.svg',
  },
  {
    name: 'Western Kentucky University',
    slug: 'western-kentucky-hilltopers',
    conference: 'Conference USA',
    division: 'FBS',
    logo: '/got1-logos/college/c-usa/western-kentucky-hilltopers.svg',
  },
  {
    name: 'United States Military Academy',
    slug: 'army',
    conference: 'FBS Independents',
    division: 'FBS',
    logo: '/got1-logos/college/independent/army.svg',
  },
  {
    name: 'University of Connecticut',
    slug: 'uconn',
    conference: 'FBS Independents',
    division: 'FBS',
    logo: '/got1-logos/college/independent/uconn.svg',
  },
  {
    name: 'University of Massachusetts Amherst',
    slug: 'umass',
    conference: 'FBS Independents',
    division: 'FBS',
    logo: '/got1-logos/college/independent/umass.svg',
  },
  {
    name: 'University of Notre Dame',
    slug: 'notre-dame',
    conference: 'FBS Independents',
    division: 'FBS',
    logo: '/got1-logos/college/independent/notre-dame.svg',
  },
  {
    name: 'Ball State University',
    slug: 'ball-state',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/ball-state.svg',
  },
  {
    name: 'Bowling Green State University',
    slug: 'bowling-green',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/bowling-green.svg',
  },
  {
    name: 'Central Michigan University',
    slug: 'central-michigan',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/central-michigan.svg',
  },
  {
    name: 'Eastern Michigan University',
    slug: 'eastern-michigan',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/eastern-michigan.svg',
  },
  {
    name: 'Kent State University',
    slug: 'kent-state',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/kent-state.svg',
  },
  {
    name: 'Miami University',
    slug: 'miami-ohio',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/miami-ohio.svg',
  },
  {
    name: 'Northern Illinois University',
    slug: 'niu',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/niu.svg',
  },
  {
    name: 'Ohio University',
    slug: 'ohio-bobcats',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/ohio-bobcats.svg',
  },
  {
    name: 'University at Buffalo',
    slug: 'buffalo',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/buffalo.svg',
  },
  {
    name: 'University of Akron',
    slug: 'akron',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/akron.svg',
  },
  {
    name: 'University of Toledo',
    slug: 'toledo',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/toledo.svg',
  },
  {
    name: 'Western Michigan University',
    slug: 'western-michigan',
    conference: 'Mid-American Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mac/western-michigan.svg',
  },
  {
    name: 'Boise State University',
    slug: 'boise-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/boise-state.svg',
  },
  {
    name: 'California State University, Fresno',
    slug: 'fresno-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/fresno-state.svg',
  },
  {
    name: 'Colorado State University',
    slug: 'colorado-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/colorado-state.svg',
  },
  {
    name: 'New Mexico State University',
    slug: 'new-mexico-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/new-mexico-state.svg',
  },
  {
    name: 'San Diego State University',
    slug: 'san-diego',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/san-diego.svg',
  },
  {
    name: 'San José State University',
    slug: 'san-jose-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/san-jose-state.svg',
  },
  {
    name: 'United States Air Force Academy',
    slug: 'air-force',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/air-force.svg',
  },
  {
    name: 'University of Hawai‘i at Mānoa',
    slug: 'hawaii',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/hawaii.svg',
  },
  {
    name: 'University of Nevada',
    slug: 'nevada',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/nevada.svg',
  },
  {
    name: 'University of Nevada, Las Vegas',
    slug: 'unlv',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/unlv.svg',
  },
  {
    name: 'University of Wyoming',
    slug: 'wyoming',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/wyoming.svg',
  },
  {
    name: 'Utah State University',
    slug: 'utah-state',
    conference: 'Mountain West Conference',
    division: 'FBS',
    logo: '/got1-logos/college/mountain-west/utah-state.svg',
  },
  {
    name: 'Oregon State University',
    slug: 'oregon-state',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/oregon-state.svg',
  },
  {
    name: 'University of California, Los Angeles',
    slug: 'university-of-california-los-angeles',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/university-of-california-los-angeles.svg',
  },
  {
    name: 'University of Oregon',
    slug: 'university-of-oregon',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/university-of-oregon.svg',
  },
  {
    name: 'University of Southern California',
    slug: 'university-of-southern-california',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/university-of-southern-california.svg',
  },
  {
    name: 'University of Washington',
    slug: 'university-of-washington',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/university-of-washington.svg',
  },
  {
    name: 'Washington State University',
    slug: 'washington-state',
    conference: 'Pac-12 Conference',
    division: 'FBS',
    logo: '/got1-logos/college/pac12/washington-state.svg',
  },
  {
    name: 'Auburn University',
    slug: 'auburn-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/auburn-university.svg',
  },
  {
    name: 'Louisiana State University',
    slug: 'louisiana-state-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/louisiana-state-university.svg',
  },
  {
    name: 'Mississippi State University',
    slug: 'mississippi-state-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/mississippi-state-university.svg',
  },
  {
    name: 'Texas A&M University',
    slug: 'texas-aandm-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/texas-aandm-university.svg',
  },
  {
    name: 'University of Alabama',
    slug: 'university-of-alabama',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-alabama.svg',
  },
  {
    name: 'University of Arkansas',
    slug: 'university-of-arkansas',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-arkansas.svg',
  },
  {
    name: 'University of Florida',
    slug: 'university-of-florida',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-florida.svg',
  },
  {
    name: 'University of Georgia',
    slug: 'university-of-georgia',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-georgia.svg',
  },
  {
    name: 'University of Kentucky',
    slug: 'university-of-kentucky',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-kentucky.svg',
  },
  {
    name: 'University of Mississippi',
    slug: 'university-of-mississippi',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-mississippi.svg',
  },
  {
    name: 'University of Missouri',
    slug: 'university-of-missouri',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-missouri.svg',
  },
  {
    name: 'University of Oklahoma',
    slug: 'university-of-oklahoma',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-oklahoma.svg',
  },
  {
    name: 'University of South Carolina',
    slug: 'university-of-south-carolina',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-south-carolina.svg',
  },
  {
    name: 'University of Tennessee',
    slug: 'university-of-tennessee',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-tennessee.svg',
  },
  {
    name: 'University of Texas',
    slug: 'university-of-texas',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/university-of-texas.svg',
  },
  {
    name: 'Vanderbilt University',
    slug: 'vanderbilt-university',
    conference: 'Southeastern Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sec/vanderbilt-university.svg',
  },
  {
    name: 'Appalachian State University',
    slug: 'app-state',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/app-state.svg',
  },
  {
    name: 'Arkansas State University',
    slug: 'arkansas-state-red-wolves',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/arkansas-state-red-wolves.svg',
  },
  {
    name: 'Coastal Carolina University',
    slug: 'coastal-carolina',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/coastal-carolina.svg',
  },
  {
    name: 'Georgia Southern University',
    slug: 'georgia-southern',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/georgia-southern.svg',
  },
  {
    name: 'Georgia State University',
    slug: 'georgia-state',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/georgia-state.svg',
  },
  {
    name: 'James Madison University',
    slug: 'jmu',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/jmu.svg',
  },
  {
    name: 'Marshall University',
    slug: 'marshall',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/marshall.svg',
  },
  {
    name: 'Old Dominion University',
    slug: 'old-dominion',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/old-dominion.svg',
  },
  {
    name: 'Texas State University',
    slug: 'texas-state',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/texas-state.svg',
  },
  {
    name: 'Troy University',
    slug: 'troy',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/troy.svg',
  },
  {
    name: 'University of Louisiana at Lafayette',
    slug: 'louisiana-ragin-cajuns',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/louisiana-ragin-cajuns.svg',
  },
  {
    name: 'University of Louisiana at Monroe',
    slug: 'louisiana-monroe',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/louisiana-monroe.svg',
  },
  {
    name: 'University of South Alabama',
    slug: 'south-alabama',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/south-alabama.svg',
  },
  {
    name: 'University of Southern Mississippi',
    slug: 'southern-miss',
    conference: 'Sun Belt Conference',
    division: 'FBS',
    logo: '/got1-logos/college/sun-belt/southern-miss.svg',
  },
  {
    name: 'California Polytechnic State University',
    slug: 'cal-poly-mustangs',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/cal-poly-mustangs.svg',
  },
  {
    name: 'California State University, Sacramento',
    slug: 'sacramento-state-hornets',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/sacramento-state-hornets.svg',
  },
  {
    name: 'Eastern Washington University',
    slug: 'eastern-washington',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/eastern-washington.svg',
  },
  {
    name: 'Idaho State University',
    slug: 'idaho-state',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/idaho-state.svg',
  },
  {
    name: 'Montana State University',
    slug: 'montana-state',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/montana-state.svg',
  },
  {
    name: 'Northern Arizona University',
    slug: 'northern-arizona-lumberjacks',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/northern-arizona-lumberjacks.svg',
  },
  {
    name: 'Portland State University',
    slug: 'portland-state-vikings',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/portland-state-vikings.svg',
  },
  {
    name: 'University of California, Davis',
    slug: 'uc-davis-aggies',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/uc-davis-aggies.svg',
  },
  {
    name: 'University of Idaho',
    slug: 'idaho-vandals',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/idaho-vandals.svg',
  },
  {
    name: 'University of Montana',
    slug: 'montana-grizzlies',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/montana-grizzlies.svg',
  },
  {
    name: 'University of Northern Colorado',
    slug: 'northern-colorado-bears',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/northern-colorado-bears.svg',
  },
  {
    name: 'Weber State University',
    slug: 'weber-state-wildcats',
    conference: 'Big Sky Conference',
    division: 'FCS',
    logo: '/got1-logos/college/big-sky/weber-state-wildcats.svg',
  },
  {
    name: 'Charleston Southern University',
    slug: 'charleston-southern',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/charleston-southern.svg',
  },
  {
    name: 'Eastern Illinois University',
    slug: 'eastern-illinois',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/eastern-illinois.svg',
  },
  {
    name: 'Gardner-Webb University',
    slug: 'gardner-web',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/gardner-web.svg',
  },
  {
    name: 'Southeast Missouri State University',
    slug: 'southeast-missouri-redhawks',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/southeast-missouri-redhawks.svg',
  },
  {
    name: 'Tennessee State University',
    slug: 'tennessee-state-university',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/tennessee-state-university.svg',
  },
  {
    name: 'Tennessee Technological University',
    slug: 'tennessee-tech-golden-eagles',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/tennessee-tech-golden-eagles.svg',
  },
  {
    name: 'University of Tennessee at Martin',
    slug: 'ut-martin-skyhawks',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/ut-martin-skyhawks.svg',
  },
  {
    name: 'Western Illinois University',
    slug: 'western-illinois-leathernecks',
    conference: 'Big South-OVC Football Association',
    division: 'FCS',
    logo: '/got1-logos/college/big-south/western-illinois-leathernecks.svg',
  },
  {
    name: 'Campbell University',
    slug: 'campbell-camels',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/campbell-camels.svg',
  },
  {
    name: 'Elon University',
    slug: 'elon',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/elon.svg',
  },
  {
    name: 'Hampton University',
    slug: 'hampton-pirates',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/hampton-pirates.svg',
  },
  {
    name: 'Howard University',
    slug: 'howard-bison-logo',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/howard-bison-logo.svg',
  },
  {
    name: 'Monmouth University',
    slug: 'monmouth',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/monmouth.svg',
  },
  {
    name: 'North Carolina A&T State University',
    slug: 'north-carolina-a-t',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/north-carolina-a-t.svg',
  },
  {
    name: 'Stony Brook University',
    slug: 'stony-brook-seawolves',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/stony-brook-seawolves.svg',
  },
  {
    name: 'Towson University',
    slug: 'towson-tigers',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/towson-univrersity.svg',
  },
  {
    name: 'University at Albany',
    slug: 'ualbany-great-danes',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/ualbany-great-danes.svg',
  },
  {
    name: 'University of Delaware',
    slug: 'delaware-fighting-hens',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/delaware-fighting-hens.svg',
  },
  {
    name: 'University of Maine',
    slug: 'maine-black-bears',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/maine-black-bears.svg',
  },
  {
    name: 'University of New Hampshire',
    slug: 'new-hampshire-wildcats',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/new-hampshire-wildcats.svg',
  },
  {
    name: 'University of Rhode Island',
    slug: 'rhode-island-rams',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/rhode-island-rams.svg',
  },
  {
    name: 'University of Richmond',
    slug: 'richmond-spiders',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/richmond-spiders.svg',
  },
  {
    name: 'Villanova University',
    slug: 'villanova',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/villanova.svg',
  },
  {
    name: 'William & Mary',
    slug: 'william-and-mary',
    conference: 'Coastal Athletic Association',
    division: 'FCS',
    logo: '/got1-logos/college/caa/william-and-mary.svg',
  },
  {
    name: 'Brown University',
    slug: 'brown',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/brown.svg',
  },
  {
    name: 'Columbia University',
    slug: 'columbia',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/columbia.svg',
  },
  {
    name: 'Cornell University',
    slug: 'cornell',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/cornell.svg',
  },
  {
    name: 'Dartmouth College',
    slug: 'dartmouth',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/dartmouth.svg',
  },
  {
    name: 'Harvard University',
    slug: 'harvard',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/harvard.svg',
  },
  {
    name: 'Princeton University',
    slug: 'princeton',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/princeton.svg',
  },
  {
    name: 'University of Pennsylvania',
    slug: 'penn',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/penn.svg',
  },
  {
    name: 'Yale University',
    slug: 'yale',
    conference: 'Ivy League',
    division: 'FCS',
    logo: '/got1-logos/college/ivy-league/yale.svg',
  },
  {
    name: 'Illinois State University',
    slug: 'illinois-state',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/illinois-state.svg',
  },
  {
    name: 'Missouri State University',
    slug: 'missouri-state-bears',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/missouri-state-bears.svg',
  },
  {
    name: 'Murray State University',
    slug: 'murray-state',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/murray-state.svg',
  },
  {
    name: 'North Dakota State University',
    slug: 'north-dakota-state-university-ndsu',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/north-dakota-state-university-ndsu.svg',
  },
  {
    name: 'South Dakota State University',
    slug: 'south-dakota-jack-rabbits',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/south-dakota-jack-rabbits.svg',
  },
  {
    name: 'Southern Illinois University',
    slug: 'southern-illinois-salukis',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/southern-illinois-salukis.svg',
  },
  {
    name: 'University of North Dakota',
    slug: 'north-dakota-fighting-hawks',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/north-dakota-fighting-hawks.svg',
  },
  {
    name: 'University of Northern Iowa',
    slug: 'northern-iowa',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/northern-iowa.svg',
  },
  {
    name: 'University of South Dakota',
    slug: 'south-dakota',
    conference: 'Missouri Valley Football Conference',
    division: 'FCS',
    logo: '/got1-logos/college/mvfc/south-dakota.svg',
  },
  {
    name: 'Central Connecticut State University',
    slug: 'central-connecticut',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/central-connecticut.svg',
  },
  {
    name: 'Duquesne University',
    slug: 'duquesne',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/duquesne.svg',
  },
  {
    name: 'Long Island University',
    slug: 'liu-sharks',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/liu-sharks.svg',
  },
  {
    name: 'Merrimack College',
    slug: 'merrimack-warriors',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/merrimack-warriors-logo.svg',
  },
  {
    name: 'Sacred Heart University',
    slug: 'sacred-heart-shu',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/sacred-heart-shuz.svg',
  },
  {
    name: 'Saint Francis University',
    slug: 'saint-francis-red-flashes',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/saint-francis-red-flashes.svg',
  },
  {
    name: 'Stonehill College',
    slug: 'stonehill-skyhawks',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/stonehill-skyhawks.svg',
  },
  {
    name: 'Wagner College',
    slug: 'wagner-seahawks',
    conference: 'Northeast Conference',
    division: 'FCS',
    logo: '/got1-logos/college/nec/wagner-seahawks.svg',
  },
  {
    name: 'Bucknell University',
    slug: 'bucknell',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/bucknell.svg',
  },
  {
    name: 'Colgate University',
    slug: 'colgate',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/colgate.svg',
  },
  {
    name: 'College of the Holy Cross',
    slug: 'holy-cross',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/holy-cross.svg',
  },
  {
    name: 'Georgetown University',
    slug: 'georgetown-hoyas',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/georgetown-hoyas.svg',
  },
  {
    name: 'Lafayette College',
    slug: 'lafayette',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/lafayette.svg',
  },
  {
    name: 'Lehigh University',
    slug: 'lehigh',
    conference: 'Patriot League',
    division: 'FCS',
    logo: '/got1-logos/college/patriot/lehigh.svg',
  },
  {
    name: 'Butler University',
    slug: 'butler',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/butler.svg',
  },
  {
    name: 'Davidson College',
    slug: 'davidson',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/davidson.svg',
  },
  {
    name: 'Drake University',
    slug: 'drake',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/drake.svg',
  },
  {
    name: 'Marist College',
    slug: 'marist-red-foxes',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/marist-red-foxes.svg',
  },
  {
    name: 'Morehead State University',
    slug: 'morehead-state-eagles',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/morehead-state-eagles.svg',
  },
  {
    name: 'Presbyterian College',
    slug: 'presbyterian-blue-hose',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/presbyterian-blue-hose.svg',
  },
  {
    name: 'Stetson University',
    slug: 'stetson-hatters',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/stetson-hatters.svg',
  },
  {
    name: 'University of Dayton',
    slug: 'dayton',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/dayton.svg',
  },
  {
    name: 'University of San Diego',
    slug: 'san-diego-toreros',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/san-diego-toreros.svg',
  },
  {
    name: 'Valparaiso University',
    slug: 'valpo',
    conference: 'Pioneer Football League',
    division: 'FCS',
    logo: '/got1-logos/college/pioneer/valpo.svg',
  },
  {
    name: 'East Tennessee State University',
    slug: 'east-tennessee-state-buccaneers',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/east-tennessee-state-buccaneers.svg',
  },
  {
    name: 'Furman University',
    slug: 'furman',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/furman.svg',
  },
  {
    name: 'Mercer University',
    slug: 'mercer-bears',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/mercer-bears.svg',
  },
  {
    name: 'Samford University',
    slug: 'samford',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/samford.svg',
  },
  {
    name: 'The Citadel',
    slug: 'citadel',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/citadel.svg',
  },
  {
    name: 'University of Tennessee at Chattanooga',
    slug: 'chatanooga',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/chatanooga.svg',
  },
  {
    name: 'Virginia Military Institute',
    slug: 'vmi-keydets',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/vmi-keydets.svg',
  },
  {
    name: 'Western Carolina University',
    slug: 'western-carolina-catamounts',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/western-carolina-catamounts.svg',
  },
  {
    name: 'Wofford College',
    slug: 'wofford',
    conference: 'Southern Conference',
    division: 'FCS',
    logo: '/got1-logos/college/socon/wofford.svg',
  },
  {
    name: 'Houston Christian University',
    slug: 'houston-christian-huskies',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/houston-christian-huskies.svg',
  },
  {
    name: 'Lamar University',
    slug: 'lamar',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/lamar.svg',
  },
  {
    name: 'McNeese State University',
    slug: 'mcneese-state-cowboys',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/mcneese-state-cowboys.svg',
  },
  {
    name: 'Nicholls State University',
    slug: 'nicholls',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/nicholls.svg',
  },
  {
    name: 'Northwestern State University',
    slug: 'northwestern-state-demons',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/northwestern-state-demons.svg',
  },
  {
    name: 'Southeastern Louisiana University',
    slug: 'southeastern-louisiana-lions',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/southeastern-louisiana-lions.svg',
  },
  {
    name: 'Stephen F. Austin State University',
    slug: 'stephen-f-autin',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/stephen-f-autin.svg',
  },
  {
    name: 'Texas A&M University–Commerce',
    slug: 'texas-a-m-commerce-lions',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/texas-a-m-commerce-lions.svg',
  },
  {
    name: 'University of the Incarnate Word',
    slug: 'incarnate-word-cardinals',
    conference: 'Southland Conference',
    division: 'FCS',
    logo: '/got1-logos/college/southland/incarnate-word-cardinals.svg',
  },
  {
    name: 'Alabama A&M University',
    slug: 'alabama-a-m',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/alabama-a-m.svg',
  },
  {
    name: 'Bethune-Cookman University',
    slug: 'bethune-cookman-bcu',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/bethune-cookman-bcu.svg',
  },
  {
    name: 'Florida A&M University',
    slug: 'famu',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/famu.svg',
  },
  {
    name: 'Grambling State University',
    slug: 'grambling',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/grambling.svg',
  },
  {
    name: 'Jackson State University',
    slug: 'jackson-state-university-jsu',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/jackson-state-university-jsu.svg',
  },
  {
    name: 'Mississippi Valley State University',
    slug: 'mississippi-valley-state-delta-devils',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/mississippi-valley-state-delta-devils.svg',
  },
  {
    name: 'Prairie View A&M University',
    slug: 'praire-view-a-m',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/praire-view-a-m.svg',
  },
  {
    name: 'Southern University',
    slug: 'southern-jaguars',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/southern-jaguars.svg',
  },
  {
    name: 'Texas Southern University',
    slug: 'texas-southern-tigers',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/texas-southern-tigers.svg',
  },
  {
    name: 'University of Arkansas at Pine Bluff',
    slug: 'arkansas-pine-bluff',
    conference: 'Southwestern Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/swac/arkansas-pine-bluff.svg',
  },
  {
    name: 'Abilene Christian University',
    slug: 'abeline-christian-acu',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/abeline-christian-acu.svg',
  },
  {
    name: 'Austin Peay State University',
    slug: 'austin-paey',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/austin-paey.svg',
  },
  {
    name: 'Eastern Kentucky University',
    slug: 'eastern-kentucky',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/eastern-kentucky.svg',
  },
  {
    name: 'Southern Utah University',
    slug: 'southern-utah-thunderbirds',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/southern-utah-thunderbirds.svg',
  },
  {
    name: 'Tarleton State University',
    slug: 'tarleton-state-texans',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/tarleton-state-texans.svg',
  },
  {
    name: 'University of Central Arkansas',
    slug: 'university-central-arkansas',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/university-central-arkansas.svg',
  },
  {
    name: 'University of North Alabama',
    slug: 'north-alabama',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/north-alabama.svg',
  },
  {
    name: 'University of West Georgia',
    slug: 'west-georgia-wolves',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/west-georgia-wolves.svg',
  },
  {
    name: 'Utah Tech University',
    slug: 'utah-tech',
    conference: 'United Athletic Conference',
    division: 'FCS',
    logo: '/got1-logos/college/uac/utah-tech.svg',
  },
  // D2 Teams
  {
    name: 'Adams State University',
    slug: 'adams-state',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/adams state.jpg',
  },
  {
    name: 'Albany State University',
    slug: 'albany-state',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/albany state.jpg',
  },
  {
    name: 'Allen University',
    slug: 'allen',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/allen.jpg',
  },
  {
    name: 'American International College',
    slug: 'american-international',
    conference: 'Northeast-10 Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/american international.jpg',
  },
  {
    name: 'Anderson University',
    slug: 'anderson',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/anderson.jpg',
  },
  {
    name: 'Angelo State University',
    slug: 'angelo-state',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/angelo state.jpg',
  },
  {
    name: 'Arkansas Tech University',
    slug: 'arkansas-tech',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/arkansas tech.jpg',
  },
  {
    name: 'University of Arkansas at Monticello',
    slug: 'arkansas-monticello',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/arkansasmonticello.jpg',
  },
  {
    name: 'Ashland University',
    slug: 'ashland',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/ashland.jpg',
  },
  {
    name: 'Assumption University',
    slug: 'assumption',
    conference: 'Northeast-10 Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/assumption.jpg',
  },
  {
    name: 'Augustana University',
    slug: 'augustana',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/augustana.jpg',
  },
  {
    name: 'Barton College',
    slug: 'barton',
    conference: 'Conference Carolinas',
    division: 'D2',
    logo: '/d2-college-football-logos/barton.jpg',
  },
  {
    name: 'Bemidji State University',
    slug: 'bemidji-state',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/bemidji state.jpg',
  },
  {
    name: 'Benedict College',
    slug: 'benedict',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/benedictg.jpg',
  },
  {
    name: 'Bentley University',
    slug: 'bentley',
    conference: 'Northeast-10 Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/bentley.jpg',
  },
  {
    name: 'Black Hills State University',
    slug: 'black-hills-state',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/black hills state.jpg',
  },
  {
    name: 'Bloomsburg University of Pennsylvania',
    slug: 'bloomsburg',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/bloomsburg.jpg',
  },
  {
    name: 'Bluefield State University',
    slug: 'bluefield-state',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/bluefield state.jpg',
  },
  {
    name: 'Bowie State University',
    slug: 'bowie-state',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/bowie state.jpg',
  },
  {
    name: 'California Baptist University',
    slug: 'california-baptist',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-california-15507800267239_sm.jpg',
  },
  {
    name: 'California University of Pennsylvania',
    slug: 'california-pa',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-california-15507800267239_sm.jpg',
  },
  {
    name: 'Carson-Newman University',
    slug: 'carson-newman',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-carson-newman-17537377150798_sm.jpg',
  },
  {
    name: 'Catawba College',
    slug: 'catawba',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-catawba-college-17537382180151_sm.jpg',
  },
  {
    name: 'Central State University',
    slug: 'central-state',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-central-state-17444741157974_sm.jpg',
  },
  {
    name: 'University of Central Missouri',
    slug: 'central-missouri',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-central-missouri-17534699583067_sm.jpg',
  },
  {
    name: 'University of Central Oklahoma',
    slug: 'central-oklahoma',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-central-oklahoma-15651472309324_sm.jpg',
  },
  {
    name: 'University of Charleston',
    slug: 'charleston',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-charleston-15959639668043_sm.jpg',
  },
  {
    name: 'Chadron State College',
    slug: 'chadron-state',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-chadron-state-15402248666164_sm.jpg',
  },
  {
    name: 'Chowan University',
    slug: 'chowan',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-chowan-15402373801594_sm.jpg',
  },
  {
    name: 'Clark Atlanta University',
    slug: 'clark-atlanta',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-clark-atlanta-17241752794566_sm.jpg',
  },
  {
    name: 'Clarion University of Pennsylvania',
    slug: 'clarion',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-clarion-15985540033762_sm.jpg',
  },
  {
    name: 'Colorado Mesa University',
    slug: 'colorado-mesa',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-colorado-mesa-15402374960225_sm.jpg',
  },
  {
    name: 'Colorado School of Mines',
    slug: 'colorado-mines',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-colorado-mines-17537409924392_sm.jpg',
  },
  {
    name: 'Colorado State University Pueblo',
    slug: 'colorado-state-pueblo',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-csu-pueblo-156514698163_sm.jpg',
  },
  {
    name: 'Concord University',
    slug: 'concord',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-concord-17539053137871_sm.jpg',
  },
  {
    name: 'Concordia University, St. Paul',
    slug: 'concordia-st-paul',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-concordia-st.-paul-17538218264839_sm.jpg',
  },
  {
    name: 'Davenport University',
    slug: 'davenport',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-davenport-17537262692997_sm.jpg',
  },
  {
    name: 'Delta State University',
    slug: 'delta-state',
    conference: 'Gulf South Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-delta-state-16423742755712_sm.jpg',
  },
  {
    name: 'East Central University',
    slug: 'east-central',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-east-central-15651468719937_sm.jpg',
  },
  {
    name: 'East Stroudsburg University of Pennsylvania',
    slug: 'east-stroudsburg',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-east-stroudsburg-1565146832979_sm.jpg',
  },
  {
    name: 'Eastern New Mexico University',
    slug: 'eastern-new-mexico',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-eastern-new-mexico-17241753325483_sm.jpg',
  },
  {
    name: 'Edinboro University of Pennsylvania',
    slug: 'edinboro',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-edinboro-17534474567777_sm.jpg',
  },
  {
    name: 'Elizabeth City State University',
    slug: 'elizabeth-city-state',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-elizabeth-city-state-17533703376799_sm.jpg',
  },
  {
    name: 'Emory & Henry College',
    slug: 'emory-henry',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-emory--henry-17241753952587_sm.jpg',
  },
  {
    name: 'Emporia State University',
    slug: 'emporia-state',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-emporia-state-17534708113875_sm.jpg',
  },
  {
    name: 'Erskine College',
    slug: 'erskine',
    conference: 'Conference Carolinas',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-erskine-15820544053547_sm.jpg',
  },
  {
    name: 'Fairmont State University',
    slug: 'fairmont-state',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-fairmont-state-15651467375543_sm.jpg',
  },
  {
    name: 'Fayetteville State University',
    slug: 'fayetteville-state',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-fayetteville-state-17533708064537_sm.jpg',
  },
  {
    name: 'Ferris State University',
    slug: 'ferris-state',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-ferris-state-17352478064993_sm.jpg',
  },
  {
    name: 'University of Findlay',
    slug: 'findlay',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-findlay-17539016351737_sm.jpg',
  },
  {
    name: 'Fort Hays State University',
    slug: 'fort-hays-state',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-fort-hays-17534725430694_sm.jpg',
  },
  {
    name: 'Fort Lewis College',
    slug: 'fort-lewis',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-fort-lewis-15402511936177_sm.jpg',
  },
  {
    name: 'Fort Valley State University',
    slug: 'fort-valley-state',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-fort-valley-15651465731512_sm.jpg',
  },
  {
    name: 'Francis Marion University',
    slug: 'francis-marion',
    conference: 'Conference Carolinas',
    division: 'D2',
    logo: '/d2-college-football-logos/FM.png',
  },
  {
    name: 'Franklin Pierce University',
    slug: 'franklin-pierce',
    conference: 'Northeast-10 Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-franklin-pierce-1547962471352_sm.jpg',
  },
  {
    name: 'Frostburg State University',
    slug: 'frostburg-state',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-frostburg-state-17241754252538_sm.jpg',
  },
  {
    name: 'Gannon University',
    slug: 'gannon',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-gannon-17534479187105_sm.jpg',
  },
  {
    name: 'Glenville State University',
    slug: 'glenville-state',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-glenville-state-15402518865457_sm.jpg',
  },
  {
    name: 'Grand Valley State University',
    slug: 'grand-valley-state',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-grand-valley-17533894899297_sm.jpg',
  },
  {
    name: 'Harding University',
    slug: 'harding',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-harding-15651464611407_sm.jpg',
  },
  {
    name: 'Henderson State University',
    slug: 'henderson-state',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-henderson-state-15651462592106_sm.jpg',
  },
  {
    name: 'Hillsdale College',
    slug: 'hillsdale',
    conference: 'Great Midwest Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-hillsdale-16619825487995_sm.jpg',
  },
  {
    name: 'Holy Family University',
    slug: 'holy-family',
    conference: 'Central Atlantic Collegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/HF.png',
  },
  {
    name: 'Indiana University of Pennsylvania',
    slug: 'indiana-pa',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-iup-17534484542011_sm.jpg',
  },
  {
    name: 'University of Jamestown',
    slug: 'jamestown',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-jamestown-1753229743127_sm.jpg',
  },
  {
    name: 'Johnson C. Smith University',
    slug: 'johnson-c-smith',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-johnson-c.-smith-17533711075043_sm.jpg',
  },
  {
    name: 'Kentucky State University',
    slug: 'kentucky-state',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-kentucky-state-17533695980028_sm.jpg',
  },
  {
    name: 'Kentucky Wesleyan College',
    slug: 'kentucky-wesleyan',
    conference: 'Great Midwest Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-kentucky-wesleyan-1565145123947_sm.jpg',
  },
  {
    name: 'Kutztown University of Pennsylvania',
    slug: 'kutztown',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-kutztown-17534489447068_sm.jpg',
  },
  {
    name: 'Lake Erie College',
    slug: 'lake-erie',
    conference: 'Great Midwest Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-lake-erie-15651450436932_sm.jpg',
  },
  {
    name: 'Lane College',
    slug: 'lane',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-lane-15402538718396_sm.jpg',
  },
  {
    name: 'Limestone University',
    slug: 'limestone',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/limestone.webp',
  },
  {
    name: 'Lincoln University',
    slug: 'lincoln-mo',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-lincoln-mo.-17538814652603_sm.jpg',
  },
  {
    name: 'Lincoln University',
    slug: 'lincoln-pa',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-lincoln-pa-17533714452123_sm.jpg',
  },
  {
    name: 'Livingstone College',
    slug: 'livingstone',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-livingstone-17533717392114_sm.jpg',
  },
  {
    name: 'Lock Haven University of Pennsylvania',
    slug: 'lock-haven',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-lock-haven-17555565243099_sm.jpg',
  },
  {
    name: 'Malone University',
    slug: 'malone',
    conference: 'Great Midwest Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/malone.png',
  },
  {
    name: 'Mars Hill University',
    slug: 'mars-hill',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-mars-hill-17537391423543_sm.jpg',
  },
  {
    name: 'University of Mary',
    slug: 'mary',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-mary-15651446832796_sm.jpg',
  },
  {
    name: 'McKendree University',
    slug: 'mckendree',
    conference: 'Great Lakes Valley Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-mckendree-172505588969_sm.jpg',
  },
  {
    name: 'Mercyhurst University',
    slug: 'mercyhurst',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/mercyhurst.png',
  },
  {
    name: 'Michigan Technological University',
    slug: 'michigan-tech',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-mtech-17537273755902_sm.jpg',
  },
  {
    name: 'Miles College',
    slug: 'miles',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-miles-15402613776279_sm.jpg',
  },
  {
    name: 'Millersville University of Pennsylvania',
    slug: 'millersville',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-millersville-15402615974872_sm.jpg',
  },
  {
    name: 'Minnesota State University, Mankato',
    slug: 'minnesota-state',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-minnesota-state-17538189953656_sm.jpg',
  },
  {
    name: 'Minnesota State University Moorhead',
    slug: 'minnesota-state-moorhead',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-msu-moorhead-17538198798386_sm.jpg',
  },
  {
    name: 'University of Minnesota Duluth',
    slug: 'minnesota-duluth',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-minnesota-duluth-15402608275043_sm.jpg',
  },
  {
    name: 'Minot State University',
    slug: 'minot-state',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-minot-state-17538194128862_sm.jpg',
  },
  {
    name: 'Mississippi College',
    slug: 'mississippi-college',
    conference: 'Gulf South Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/mississippi college.png',
  },
  {
    name: 'Midwestern State University',
    slug: 'midwestern-state',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-midwestern-state-15402609937904_sm.jpg',
  },
  {
    name: 'Missouri Southern State University',
    slug: 'missouri-southern',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-missouri-southern-154023150577_sm.jpg',
  },
  {
    name: 'Missouri Western State University',
    slug: 'missouri-western',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-missouri-western-17534846478623_sm.jpg',
  },
  {
    name: 'University of Mount Olive',
    slug: 'mount-olive',
    conference: 'Conference Carolinas',
    division: 'D2',
    logo: '/d2-college-football-logos/mount olive.png',
  },
  {
    name: 'Morehouse College',
    slug: 'morehouse',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-morehouse-15402621257916_sm.jpg',
  },
  {
    name: 'New Haven University',
    slug: 'new-haven',
    conference: 'Northeast-10 Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/new haven.png',
  },
  {
    name: 'New Mexico Highlands University',
    slug: 'new-mexico-highlands',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-new-mexico-highlands-17243753279806_sm.jpg',
  },
  {
    name: 'Newberry College',
    slug: 'newberry',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-newberry1-17537395842992_sm.jpg',
  },
  {
    name: 'Northeastern State University',
    slug: 'northeastern-state',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-northeastern-state-15402317400956_sm.jpg',
  },
  {
    name: 'Northern Michigan University',
    slug: 'northern-michigan',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-northern-mich-17537296478735_sm.jpg',
  },
  {
    name: 'Northern State University',
    slug: 'northern-state',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-northern-state-15402625519521_sm.jpg',
  },
  {
    name: 'North Greenville University',
    slug: 'north-greenville',
    conference: 'Conference Carolinas',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-north-greenville-17538804909813_sm.jpg',
  },
  {
    name: 'Northwestern Oklahoma State University',
    slug: 'northwestern-oklahoma-state',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-northwestern-oklahoma-15402625893251_sm.jpg',
  },
  {
    name: 'Northwest Missouri State University',
    slug: 'northwest-missouri-state',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-northwest-missouri-17533934136235_sm.jpg',
  },
  {
    name: 'Northwood University',
    slug: 'northwood',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-northwood-17241755751869_sm.jpg',
  },
  {
    name: 'Notre Dame College',
    slug: 'notre-dame-oh',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/notre dame college.webp',
  },
  {
    name: 'Oklahoma Baptist University',
    slug: 'oklahoma-baptist',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-oklahoma-baptist-15402627760832_sm.jpg',
  },
  {
    name: 'Oklahoma Christian University',
    slug: 'oklahoma-christian',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/oklahoma christian.png',
  },
  {
    name: 'Ohio Dominican University',
    slug: 'ohio-dominican',
    conference: 'Great Midwest Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-ohio-dominican-17539021677197_sm.jpg',
  },
  {
    name: 'Ouachita Baptist University',
    slug: 'ouachita-baptist',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-ouachita-17537249949437_sm.jpg',
  },
  {
    name: 'Pace University',
    slug: 'pace',
    conference: 'Northeast-10 Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-pace-15402628275717_sm.jpg',
  },
  {
    name: 'Pittsburg State University',
    slug: 'pittsburg-state',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-pittsburg-state-17534854242819_sm.jpg',
  },
  {
    name: 'Post University',
    slug: 'post',
    conference: 'Central Atlantic Collegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-post-16126322471299_sm.jpg',
  },
  {
    name: 'Saginaw Valley State University',
    slug: 'saginaw-valley-state',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-saginaw-17537304175487_sm.jpg',
  },
  {
    name: 'Saint Anselm College',
    slug: 'saint-anselm',
    conference: 'Northeast-10 Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-saint-anselm-17538224790478_sm.jpg',
  },
  {
    name: 'Saint Augustine\'s University',
    slug: 'st-augustines',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/saint augustine.png',
  },
  {
    name: 'Savannah State University',
    slug: 'savannah-state',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-savannah-state-15622873985345_sm.jpg',
  },
  {
    name: 'Seton Hill University',
    slug: 'seton-hill',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-seton-hill-15402629053842_sm.jpg',
  },
  {
    name: 'Shaw University',
    slug: 'shaw',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-shaw-17533720039991_sm.jpg',
  },
  {
    name: 'Shepherd University',
    slug: 'shepherd',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-shepherd-17534506960245_sm.jpg',
  },
  {
    name: 'Shippensburg University of Pennsylvania',
    slug: 'shippensburg',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-shippensburg-17575396175014_sm.jpg',
  },
  {
    name: 'Shorter University',
    slug: 'shorter',
    conference: 'Gulf South Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-shorter-15402630183188_sm.jpg',
  },
  {
    name: 'University of Sioux Falls',
    slug: 'sioux-falls',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-sioux-falls-17533922069949_sm.jpg',
  },
  {
    name: 'Slippery Rock University of Pennsylvania',
    slug: 'slippery-rock',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-slippery-rock-17534516029608_sm.jpg',
  },
  {
    name: 'South Dakota School of Mines and Technology',
    slug: 'south-dakota-mines',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-sd-mines-17537415678913_sm.jpg',
  },
  {
    name: 'Southeastern Oklahoma State University',
    slug: 'southeastern-oklahoma-state',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-southeastern-oklahoma-17533673676527_sm.jpg',
  },
  {
    name: 'Southern Arkansas University',
    slug: 'southern-arkansas',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-southern-arkansas-17537256958923_sm.jpg',
  },
  {
    name: 'Southern Connecticut State University',
    slug: 'southern-connecticut-state',
    conference: 'Northeast-10 Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-southern-connecticut-17533670840436_sm.jpg',
  },
  {
    name: 'Southwest Baptist University',
    slug: 'southwest-baptist',
    conference: 'Great Lakes Valley Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-southwest-baptist-17538940286077_sm.jpg',
  },
  {
    name: 'Southwest Minnesota State University',
    slug: 'southwest-minnesota-state',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-southwest-minnesota-state-17538203253511_sm.jpg',
  },
  {
    name: 'Southwestern Oklahoma State University',
    slug: 'southwestern-oklahoma-state',
    conference: 'Great American Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-southwestern-oklahoma-17241756447497_sm.jpg',
  },
  {
    name: 'Stonehill College',
    slug: 'stonehill',
    conference: 'Northeast-10 Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/stonehill.png',
  },
  {
    name: 'Tarleton State University',
    slug: 'tarleton-state',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/tarleton.svg',
  },
  {
    name: 'Texas A&M University-Commerce',
    slug: 'texas-am-commerce',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/texas-a&m-university-commerce.png',
  },
  {
    name: 'Texas A&M University-Kingsville',
    slug: 'texas-am-kingsville',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-texas-am-kingsville-15651429020349_sm.jpg',
  },
  {
    name: 'University of Texas Permian Basin',
    slug: 'texas-permian-basin',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-ut-permian-basin-17539041240919_sm.jpg',
  },
  {
    name: 'University of Texas at Tyler',
    slug: 'texas-tyler',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/texas at tyler.jpg',
  },
  {
    name: 'Tiffin University',
    slug: 'tiffin',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-tiffin-17243636402468_sm.jpg',
  },
  {
    name: 'Truman State University',
    slug: 'truman-state',
    conference: 'Great Lakes Valley Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-truman-state-17539000643267_sm.jpg',
  },
  {
    name: 'Tusculum University',
    slug: 'tusculum',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-tusculum-15402626524301_sm.jpg',
  },
  {
    name: 'Tuskegee University',
    slug: 'tuskegee',
    conference: 'Southern Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-tuskegee-15402643503641_sm.jpg',
  },
  {
    name: 'Upper Iowa University',
    slug: 'upper-iowa',
    conference: 'Great Lakes Valley Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-upper-iowa-17539007974026_sm.jpg',
  },
  {
    name: 'University of Virginia\'s College at Wise',
    slug: 'uva-wise',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-uva-wise-17241757076059_sm.jpg',
  },
  {
    name: 'Valdosta State University',
    slug: 'valdosta-state',
    conference: 'Gulf South Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-valdosta-state-17533794256688_sm.jpg',
  },
  {
    name: 'Virginia State University',
    slug: 'virginia-state',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-virginia-state-17533722802064_sm.jpg',
  },
  {
    name: 'Virginia Union University',
    slug: 'virginia-union',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-virginia-union-17575424219505_sm.jpg',
  },
  {
    name: 'Walsh University',
    slug: 'walsh',
    conference: 'Great Midwest Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-walsh-15651424456076_sm.jpg',
  },
  {
    name: 'Washburn University',
    slug: 'washburn',
    conference: 'Mid-America Intercollegiate Athletics Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-washburn-17534859052325_sm.jpg',
  },
  {
    name: 'Wayne State University',
    slug: 'wayne-state-mi',
    conference: 'Great Lakes Intercollegiate Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-wayne-state-17537309793021_sm.jpg',
  },
  {
    name: 'Wayne State College',
    slug: 'wayne-state-ne',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-wayne-state-neb.-17538208780632_sm.jpg',
  },
  {
    name: 'West Chester University of Pennsylvania',
    slug: 'west-chester',
    conference: 'Pennsylvania State Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-west-chester-17534522805068_sm.jpg',
  },
  {
    name: 'University of West Alabama',
    slug: 'west-alabama',
    conference: 'Gulf South Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-west-alabama-17533799684744_sm.jpg',
  },
  {
    name: 'University of West Florida',
    slug: 'west-florida',
    conference: 'Gulf South Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-west-florida-1753380408082_sm.jpg',
  },
  {
    name: 'University of West Georgia',
    slug: 'west-georgia',
    conference: 'Gulf South Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/west georgia.png',
  },
  {
    name: 'West Liberty University',
    slug: 'west-liberty',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-west-liberty-15651420799777_sm.jpg',
  },
  {
    name: 'West Texas A&M University',
    slug: 'west-texas-am',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-west-texas-am-15651400304693_sm.jpg',
  },
  {
    name: 'West Virginia State University',
    slug: 'west-virginia-state',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-west-virginia-state-17539058471654_sm.jpg',
  },
  {
    name: 'West Virginia Wesleyan College',
    slug: 'west-virginia-wesleyan',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-west-virginia-wesleyan-15402662022462_sm.jpg',
  },
  {
    name: 'Western Colorado University',
    slug: 'western-colorado',
    conference: 'Rocky Mountain Athletic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-western-colorado-15651419911943_sm.jpg',
  },
  {
    name: 'Western New Mexico University',
    slug: 'western-new-mexico',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-western-new-mexico-15402662620146_sm.jpg',
  },
  {
    name: 'Western Oregon University',
    slug: 'western-oregon',
    conference: 'Lone Star Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-western-oregon-17241757836952_sm.jpg',
  },
  {
    name: 'Wheeling University',
    slug: 'wheeling',
    conference: 'Mountain East Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-wheeling-jesuit-15508802715379_sm.jpg',
  },
  {
    name: 'William Jewell College',
    slug: 'william-jewell',
    conference: 'Great Lakes Valley Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-william-jewell-15651418963418_sm.jpg',
  },
  {
    name: 'Wingate University',
    slug: 'wingate',
    conference: 'South Atlantic Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-wingate1-17537401443169_sm.jpg',
  },
  {
    name: 'Winona State University',
    slug: 'winona-state',
    conference: 'Northern Sun Intercollegiate Conference',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-winona-state-1753821317091_sm.jpg',
  },
  {
    name: 'Winston-Salem State University',
    slug: 'winston-salem-state',
    conference: 'Central Intercollegiate Athletic Association',
    division: 'D2',
    logo: '/d2-college-football-logos/sch-winston-salem-state-17533728611274_sm.jpg',
  },
]
